export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const CLEAR_DATA = 'CLEAR_DATA';

export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_TAST_ERROR = 'ADD_RECIPE_TAST_ERROR';
export const ADD_RECIPE_TAST_PROGRESS = 'ADD_RECIPE_TAST_PROGRESS';

export const GET_RECEPIES = 'GET_RECEPIES';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const ADD_TO_CUSTOM_LIST = 'ADD_TO_CUSTOM_LIST';
export const EDIT_RECIPE = 'EDIT_RECIPE';
