export const USER_STATE_CHANGE = "USER_STATE_CHANGE"
export const CLEAR_DATA = "CLEAR_DATA"

export const ADD_RECIPE_TAST_ERROR = "ADD_RECIPE_TAST_ERROR"
export const ADD_RECIPE_TAST_PROGRESS = "ADD_RECIPE_TAST_PROGRESS"

export const GET_RECEPIES = "GET_RECEPIES"
export const DELETE_RECIPE = "DELETE_RECIPE"
export const ADD_TO_CUSTOM_LIST = "ADD_TO_CUSTOM_LIST"
export const EDIT_RECIPE = "EDIT_RECIPE"
export const ADD_RECIPE_MESSAGE = "ADD_RECIPE_MESSAGE"
export const DELETE_CUSTOM_LIST_ITEM = "DELETE_CUSTOM_LIST_ITEM"
export const GET_ALL_RECIPES = "GET_ALL_RECIPES"
export const GET_CUSTOM_LIST = "GET_CUSTOM_LIST"
